services:
  - type: web
    name: fastapi-bg-removal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
    pythonVersion: 3.9.0