services:
  - type: web
    name: fastapi-bg-removal
    env: python
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    pythonVersion: 3.9.0